

# Introduction {#intro}

`r if(identical(gitbook_on, FALSE)) knitr::asis_output(paste0("This report is available as a PDF and as an online interactive report at ", ngr::ngr_str_link_url(url_base = params$report_url, anchor_text = params$report_url), ". We recommend viewing online as the web-hosted HTML version contains more features and is more easily navigable. Please reference the website for the latest PDF from ", ngr::ngr_str_link_url(url_base = params$repo_url, url_resource = "raw/main/docs/fish_passage_fraser_2024.pdf", anchor_text = "fish_passage_fraser_2024.pdf"), "."))`

`r if(identical(gitbook_on, FALSE)){knitr::asis_output("<br>")}`

Since 2023, the Society for Ecosystem Restoration Northern British Columbia (SERNbc), with funding from the Ministry of Transportation and Infrastructure, has been actively involved in planning, coordinating, and conducting fish passage restoration efforts within the Upper Fraser River watershed. The primary objective of this project is to identify and prioritize fish passage barriers within these study areas,
develop comprehensive restoration plans to address these barriers, and foster momentum for broader ecosystem restoration
initiatives. While the primary focus is on fish passage, this work also serves as a lens through which to view the
broader ecosystems, leveraging efforts to build capacity for ecosystem restoration and improving our understanding of
watershed health. We recognize that the health of life - such as our own - and the health of our surroundings are
interconnected, with our overall well-being dependent on the health of our environment.

<br>


The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing habitat [@bramblett_etal2002SeasonalUse; @swalesRoleOffChannelPonds1989; @diebel_etal2015EffectsRoad].  Culverts can present barriers to fish migration due to low water depth, increased water velocity, turbulence, a vertical drop at the culvert outlet and/or maintenance issues [@slaneyFishHabitatRehabilitation1997; @cote_etal2005Fishpassage]. As road crossing structures are commonly upgraded or removed there are numerous opportunities to restore connectivity by ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation designs. 

<br>

Although remediation and replacement of stream crossing structures can have benefits to local fish populations, the costs of remedial works can be significant and the impacts of the work often complex to evaluate and quantify. Additionally, allocation of ecosystem restoration funding towards infrastructure upgrades on transportation right of ways are not always considered ethical under all circumstances from all perspectives. When funds are finite and invested groups are engaged in fund raising, cost benefits and the ethics of crossing replacements should be explored collaboratively alongside the cost benefits and ethics of alternative investment activities including transportation corridor relocation/deactivation, land procurement/covenant, cattle exclusion, riparian/floodplain restoration, habitat complexing, water conservation,  commercial/recreational fishing management, salt water interventions and research.

<br>

Please note that at the time of reporting this document can be considered a living document. Version numbers are logged for each release with modifications, enhancements, and other changes tracked in the [Changelog](#changelog) with issues and proposed/planned enhancements tracked `r ngr::ngr_str_link_url(url_base = params$repo_url, url_resource = "issues", anchor_text = "here")`.
