# Results

```{r ld-db}
sites_all <- fpr::fpr_db_query(
  query = "SELECT * FROM working.fp_sites_tracking"
)
```

```{r summarize-sites}

# unique(sites_all$watershed_group_name)
# 
wsg <- c(
  "Lower Chilako River",
  "Willow River",
  "Tabor River",
  "Upper Fraser River",
  "Nechako River",
  "Morkill River",
  "Francois Lake"
)

# more straight forward is new graph only watersheds
# wsg_ng <- "Elk River"

# here is a summary with Elk watershed group removed
sites_all_summary <- sites_all |> 
  # make a flag column for uav flights
  dplyr::mutate(
    uav = dplyr::case_when(
      !is.na(link_uav1) ~ "yes",
      T ~ NA_character_
    )) |> 
  # remove the elk counts
  dplyr::filter(watershed_group %in% wsg) |>
  dplyr::group_by(watershed_group) |> 
  dplyr::summarise(
    dplyr::across(assessment:fish_sampling, ~ sum(!is.na(.x))),
    uav = sum(!is.na(uav))
  ) |> 
  sf::st_drop_geometry() |> 
  # make pretty names
  dplyr::rename_with(~ stringr::str_replace_all(., "_", " ") |> 
                       stringr::str_to_title()) |> 
  # annoying special case
  dplyr::rename(
    `Drone Imagery` = Uav) |> 
  janitor::adorn_totals()
```

```{r tab-sites-sum-cap, results="asis"}
my_caption = "Summary of fish passage assessment procedures conducted in the Fraser through SERNbc since 2023"
my_tab_caption()
```

```{r tab-sites-sum}
sites_all_summary |> 
  my_dt_table(
    page_length = 20,
    cols_freeze_left = 0
              )
```

<br>


```{r tab-sites-cap, results="asis"}
my_caption = "Details of fish passage assessment procedures conducted in the Fraser through SERNbc since 2023."
my_tab_caption()
```

```{r tab-sites-all}
sites_all |>
  sf::st_drop_geometry() |>
  dplyr::filter(watershed_group %in% wsg) |>
  dplyr::relocate(watershed_group, .after = my_crossing_reference) |> 
  dplyr::select(-idx) |>
  # make pretty names
  dplyr::rename_with(~ . |>
                       stringr::str_replace_all("_", " ") |>
                       stringr::str_replace_all("repo", "Report") |>
                       stringr::str_replace_all("uav", "Drone") |>
                       stringr::str_to_title()) |> 
  # dplyr::arrange(desc(stream_crossing_id)) |> 
  
  my_dt_table(
    cols_freeze_left = 1,
    escape = FALSE
  )
```

